### ISSUE TITLE
Disable Vanilla Trees?

### ISSUE THREAD

**Issue by TheSexyYeti** [Darkhax-Minecraft/No-Worldgen-5-You#5]
Can your mod be used to disable vanilla trees?. I've got dynamic trees installed in my modpack. but for some reason it's not completely replacing every tree. I talked to the creator of Dynamic Trees and he said this his mod is dependent on biomes. So if I can completely disable vanilla trees then only Dynamic Trees will generate.

**Comment by Darkhax** [comment]
No sorry, this mod is only supports structure generation currently.
