### ISSUE TITLE
[QUESTION] <title> Can this be used to disable the dungeons in Galacticraft

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/No-Worldgen-5-You#6]
### Question

I have been trying to disable the dungeons in Galacticraft, can this do that?

**Comment by Darkhax** [comment]
It depends on how Galacticraft registers structures. You can check this by installing the mod and searching the config file for galacticraft. Keep in mind that 1.12.2 support is not longer being maintained.
